export const LOAD_DEFAULT_ITEMS = 'LOAD_DEFAULT_ITEMS';
export const SET_DEFAULT_ITEMS = 'SET_DEFAULT_ITEMS';
export const MOVE_TO_TARGET = 'MOVE_TO_TARGET';
export const SET_ACTIVE_ITEM = 'SET_ACTIVE_ITEM';
export const SET_VALID_DRAG = 'SET_VALID_DRAG';
